repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.1
    hooks:
      - id: ruff
        # --fix enables auto-fixing linting errors.
        args: [--fix]
      - id: ruff-format
